<?php
$CONFIG = array (
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'secret' => 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.mydomain.ru',
    1 => 'onlyoffice.mydomain',
    2 => 'localhost',
  ),
  'trusted_proxies' => 
  array (
    0 => 'proxyserver.mydomain.ru',
    1 => '127.0.0.1',
    2 => '::1',
    3 => 'localhost',
  ),
  'overwritecondaddr' => '^192\\.168\\.50\\.10$',
  'overwritehost' => 'nextcloud.mydomain.ru',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'overwrite.cli.url' => 'https://nextcloud.mydomain.ru',
  'datadirectory' => '/data',
  'dbtype' => 'mysql',
  'version' => '24.0.3.2',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'dbuser',
  'dbpassword' => 'dbpassword',
  'installed' => true,
  'instanceid' => 'ocuentg79zji',
  'activity_expire_days' => 14,
  'allow_local_remote_servers' => true,
  'auth.bruteforce.protection.enabled' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
    1 => 'Thumbs.db',
    2 => 'thumbs.db',
  ),
 'cron_log' => true,
  'default_phone_region' => 'RU',
  'force_language' => 'ru',
  'default_locale' => 'ru_RU',
  'defaultapp' => 'dashboard,files',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\Movie',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\PSD',
    10 => 'OC\\Preview\\AI',
    11 => 'OC\\Preview\\EPS',
    12 => 'OC\\Preview\\TIFF',
    13 => 'OC\\Preview\\MP4',
    14 => 'OC\\Preview\\MOV',
    15 => 'OC\\Preview\\HEIC',
    16 => 'OC\\Preview\\MarkDown',
    17 => 'OC\\Preview\\OpenDocument',
    18 => 'OC\\Preview\\Krita',
    19 => 'OC\\Preview\\Illustrator',
    20 => 'OC\\Preview\\MSOffice2003',
    21 => 'OC\\Preview\\MSOffice2007',
    22 => 'OC\\Preview\\MSOfficeDoc',
    23 => 'OC\\Preview\\SVG',
    24 => 'OC\\Preview\\MKV',
    25 => 'OC\\Preview\\Photoshop',
    26 => 'OC\\Preview\\Postscript',
    27 => 'OC\\Preview\\StarOffice',
    28 => 'OC\\Preview\\AVI',
    29 => 'OC\\Preview\\Font',
  ),
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'filesystem_check_changes' => 0,
  'htaccess.RewriteBase' => '/',
  'integrity.check.disabled' => false,
  'knowledgebaseenabled' => false,
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Moscow',
  'log_rotate_size' => '104857600',
  'maintenance' => false,
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'jpeg_quality' => 80,
  'preview_max_scale_factor' => 1,
  'preview_max_memory' => 1024,
  'preview_max_filesize_image' => -1,
  'profile.enabled' => false,
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.5,
    'dbindex' => 1,
  ),
  'quota_include_external_storage' => false,
  'share_folder' => '/Public',
  'skeletondirectory' => '',
  'theme' => '',
  'trashbin_retention_obligation' => 'auto, 180',
  'versions_retention_obligation' => 'auto, 360',
  'updater.release.channel' => 'stable',
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
);
